### ISSUE TITLE
행사이름 정하기

### ISSUE THREAD

**Issue by binsoopark** [gdgsuwon/solocoding2019#1]
후보: 극한 코딩, 개발인의 이중생활, 해피개발데이투유, 프로그래머 랩소디, 나혼자 개발한다, 어서와 개발은 처음이지, 솔로코딩, SOLODEV,기타?

재석
- [ ] 극한 코딩
- [ ] 개발인의 이중생활
- [ ] 해피개발데이투유
- [ ] 프로그래머 랩소디
- [x] 나혼자 개발한다
- [x] 어서와 개발은(플러터는) 처음이지
- [ ] 솔로코딩
- [ ] SOLODEV
- [x] 기타의견 나혼자코딩한다

진호
- [ ] 극한 코딩
- [ ] 개발인의 이중생활
- [ ] 해피개발데이투유
- [ ] 프로그래머 랩소디
- [ ] 나혼자 개발한다
- [ ] 어서와 개발은(플러터는) 처음이지
- [ ] 솔로코딩
- [ ] SOLODEV
- [ ] 기타의견

수빈
- [ ] 극한 코딩
- [ ] 개발인의 이중생활
- [ ] 해피개발데이투유
- [ ] 프로그래머 랩소디
- [ ] 나혼자 개발한다
- [ ] 어서와 개발은(플러터는) 처음이지
- [ ] 솔로코딩
- [ ] SOLODEV
- [ ] 기타의견

**Comment by binsoopark** [comment]
원하시는 이름 체크해주심되요

**Comment by binsoopark** [comment]
@yjaeseok @romandev 
나혼자코딩한다 ->
이걸로 할까 하지만 라임이 안살아서 그런데, "나 코딩 한다" 정도로 짧게 줄이면 어때요?
부제로 'Flutter 편'이라고 달면 좋지 않을까 싶어요~

**Comment by yjaeseok** [comment]
좋은의견입니다 나 코딩한다!
