### ISSUE TITLE
홍보에 담아야 할 내용 정하기

### ISSUE THREAD

**Issue by binsoopark** [gdgsuwon/solocoding2019#2]
댓글로 필요한 내용 기록
행사이름은?
날짜 확정?
내용도 확정?
배너제작
컨셉확정

위에 대한 내용을 보고 의견있음 댓글 남겨주세요! 낼 저녁까지.ㅋ

**Comment by yjaeseok** [comment]
행사이름은 타 이슈로 관리되는듯 함ㅋ 거기에 의견남겼어요!

날짜확정 : 날짜는 저번에 이야기한대로 ㄱㄱ
내용도 확정 : 어떤주제를 참석자들에게 줄지만 고르면 될것같아요
배너제작 : 배너는 어떤걸말하나요?
컨셉확정 : 현재 컨셉대로! 행사이름에 따라 브랜딩만 하면 될것같아요

**Comment by binsoopark** [comment]
![pangyo1](https://user-images.githubusercontent.com/6077774/52913903-b53c6d00-3305-11e9-847d-bf67dfb022b4.jpg)
![android1](https://user-images.githubusercontent.com/6077774/52913905-ba99b780-3305-11e9-9ba0-0a3b45ca0863.jpg)

배너는 이런걸 이야기 한 거 였어요.ㅎ
적당한 이미지 하나정도는 있으면 좋지 않을까 싶었는데, 뭐... 일단은 텍스트만이라도 정리해서 facebook에 올리면 좋겠네요.

**Comment by yjaeseok** [comment]
아하 ㅋ 행사이름을 정하면 배너제작을 바로 고고하죠

**Comment by binsoopark** [comment]
![_flutter](https://user-images.githubusercontent.com/6077774/53300291-9b140900-3888-11e9-86f3-6519d91b95ff.png)

[나코딩한다.zip](https://github.com/gdgsuwon/solocoding2019/files/2897964/default.zip)


위에 있는 이미지를 중심으로 내용을 정하면 될 것 같습니다. 리소스는 별도로 첨부했습니다.

처음에 계획했던 23일부터 홍보는 이미 지나갔고.. 바로 하는것도 어려울것 같으므로... 3월 1일에 접수와 함께 홍보를 시작하는걸로 해야할것같습니다.

**Comment by yjaeseok** [comment]
3월 1일부터 참가신청 ~ 15일
3월 25일 ~ 4월 5일 개발 
4월 6일 오프라인 발표
